### PR TITLE
TECH-2111 Bitstamp generic crypto withdrawal api method

### PR DESCRIPTION
**Pull request by jolind93**
- Implement crypto withdrawal with path param for crypto
- Use new withdrawal method instead of method reflection

### CODE REVIEW

**Review by this-juan — APPROVED** [review]
LGTM

**Comment by jolind93** [comment]
> LGTM

Hmm, I guess one issue with this megre is that it will affect your PR in the XChange repo?

**Comment by this-juan** [comment]
> > LGTM
> 
> Hmm, I guess one issue with this megre is that it will affect your PR in the XChange repo?

The one that no one cares about? Not sure it will make much difference.

**Comment by jolind93** [comment]
> > > LGTM
> > 
> > 
> > Hmm, I guess one issue with this megre is that it will affect your PR in the XChange repo?
> 
> The one that no one cares about? Not sure it will make much difference.

Okay. Then I'm leaving it up to you to build/prepare(?) it for our usage. I'm unsure how to do that, how how you did it the first time. Will we need to update some kind of version?

**Pull request merged**
